
dot pie: ".py"
dot Talon: ".talon"
dot to do: ".todo"
dot MD: ".md"
dot JS: ".js"
dot HTML: ".html"
dot CSS: ".css"
dot Java: ".java"
dot (C sharp | CS): ".cs"
dot H: ".h"
dot CPP: ".cpp"
dot TS: ".ts"
dot GO: ".go"
dot SH: ".sh"
dot CSV: ".csv"